import Link from "next/link";

export const metadata = { title: "Terms of Use — Dish Report" };

export default function TermsPage() {
  return (
    <div style={{
      background: "#F2EEE8", minHeight: "100vh",
      fontFamily: "'Inter', -apple-system, sans-serif",
    }}>
      {/* Header */}
      <div style={{
        borderBottom: "1px solid #E8E3DC",
        padding: "20px 24px",
        display: "flex", alignItems: "center", gap: 16,
        background: "#F2EEE8",
      }}>
        <Link href="/" style={{
          fontFamily: "var(--font-orbitron), 'Courier New', monospace",
          fontSize: "1.1rem", fontWeight: 900, color: "#1C1917",
          letterSpacing: "0.04em", textDecoration: "none",
        }}>
          DISH REPORT
        </Link>
        <span style={{ color: "#D4CBC0", fontFamily: "'IBM Plex Mono', monospace", fontSize: "0.75rem" }}>
          /
        </span>
        <span style={{
          fontFamily: "'Sevastopol', Georgia, serif",
          fontSize: "0.625rem", color: "#B8780A",
          textTransform: "uppercase", letterSpacing: "0.15em",
        }}>
          Terms of Use
        </span>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "48px 24px 80px" }}>

        {/* Title */}
        <div style={{
          fontFamily: "'Playfair Display', Georgia, serif",
          fontSize: "2rem", fontWeight: 700, color: "#1C1917",
          marginBottom: 8,
        }}>Terms of Use</div>
        <div style={{
          fontFamily: "'Sevastopol', Georgia, serif",
          fontSize: "0.625rem", color: "#A89F99",
          textTransform: "uppercase", letterSpacing: "0.15em",
          marginBottom: 40,
        }}>
          Last updated: May 2026
        </div>

        {/* Intro */}
        <p style={body}>
          Dish Report (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) provides food intelligence
          tools that help you find great food. By creating an account you agree to
          these terms. If you don&apos;t agree, please don&apos;t create an account.
        </p>

        <Section heading="1. What We Do With Your Data">
          <p style={body}>
            When you use Dish Report — searching for dishes, saving favorites, building lists —
            your activity contributes to our anonymized food database. This means:
          </p>
          <ul style={list}>
            <li>We record what people search for and what they save.</li>
            <li>This data is <strong>anonymized</strong> before any use outside your own account.
            Your name, email, and identity are never attached to contributed data.</li>
            <li>Aggregated, anonymized search and save patterns may appear in
            house-branded content — for example, &quot;Most saved birria spots in San Diego&quot;
            or a Dish Report editorial feature on top-rated omakase restaurants.</li>
            <li>We do not sell your personal data to third parties.</li>
          </ul>
        </Section>

        <Section heading="2. Your Account">
          <p style={body}>
            You are responsible for keeping your password secure. You must be at least 13 years
            old to create an account. You may delete your account at any time from your
            profile settings; deletion removes your personal data from our systems
            within 30 days.
          </p>
        </Section>

        <Section heading="3. The Service">
          <p style={body}>
            Dish Report is a food discovery tool. Restaurant scores and recommendations are
            generated by AI from public review data. They are informational only — we don&apos;t
            guarantee accuracy and we are not responsible for the quality of any restaurant
            or dish you visit based on our recommendations.
          </p>
          <p style={body}>
            We may change, suspend, or discontinue any part of the service at any time.
            We&apos;ll give reasonable notice for significant changes that affect your account.
          </p>
        </Section>

        <Section heading="4. Acceptable Use">
          <p style={body}>
            Don&apos;t use Dish Report to scrape data, attempt unauthorized access, or do anything
            illegal. Don&apos;t create fake accounts or misrepresent yourself. We may terminate
            accounts that violate these terms.
          </p>
        </Section>

        <Section heading="5. Intellectual Property">
          <p style={body}>
            The Dish Report name, logo, and original content are owned by us. Restaurant data
            is sourced from public reviews and third-party APIs. You may not copy or redistribute
            our food intelligence reports without permission.
          </p>
        </Section>

        <Section heading="6. Liability">
          <p style={body}>
            Dish Report is provided &quot;as is&quot; without warranties of any kind.
            To the extent permitted by law, we are not liable for any indirect, incidental,
            or consequential damages arising from your use of the service.
          </p>
        </Section>

        <Section heading="7. Contact">
          <p style={body}>
            Questions about these terms? Email us at{" "}
            <a href="mailto:hello@dishreport.com" style={{ color: "#B8780A" }}>
              hello@dishreport.com
            </a>
            . We&apos;re a small team and we do read every message.
          </p>
        </Section>

        {/* Back link */}
        <div style={{ marginTop: 48 }}>
          <Link href="/" style={{
            fontFamily: "'Sevastopol', Georgia, serif",
            fontSize: "0.625rem", color: "#B8780A",
            textTransform: "uppercase", letterSpacing: "0.15em",
            textDecoration: "none",
          }}>
            ← Back to Dish Report
          </Link>
        </div>
      </div>
    </div>
  );
}

// ─── Style helpers ────────────────────────────────────────────────────────────
const body: React.CSSProperties = {
  fontFamily: "'DM Sans', 'Inter', sans-serif",
  fontSize: "0.9375rem", color: "#2D2826",
  lineHeight: 1.75, marginBottom: 16,
};

const list: React.CSSProperties = {
  fontFamily: "'DM Sans', 'Inter', sans-serif",
  fontSize: "0.9375rem", color: "#2D2826",
  lineHeight: 1.75, marginBottom: 16,
  paddingLeft: 20,
};

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <div style={{
        fontFamily: "'Sevastopol', Georgia, serif",
        fontSize: "0.625rem", color: "#B8780A",
        textTransform: "uppercase", letterSpacing: "0.15em",
        marginBottom: 10,
      }}>{heading}</div>
      {children}
    </div>
  );
}
